In [ ]:
# import sys
# from pathlib import Path

# # Get the absolute path to the project root
# notebook_path = Path('/Users/nirmal/Documents/np_research/ManGo_code/ManGo')
# project_root = str(notebook_path)

# # Add the project root to Python path if it's not already there
# if project_root not in sys.path:
#     sys.path.insert(0, project_root)

# # Now you can import your module
# from machinegnostics.magcal import gmedian

# # Verify the import worked
# print(f"Project root: {project_root}")
# print(f"Available at: {gmedian.__module__}")

In [ ]:

# Sample data
import numpy as np
data = np.array([1.2, 2.3, 3.4, 4.5, 5.6])

# Using function directly
g_median_quant = gmedian(data, case='j')
print(f"i G-median: {g_median_quant:.4f}")

g_median_esti = gmedian(data, case='i')
print(f"j G-median: {g_median_esti:.4f}")

In [ ]:
print(f'median {np.median(data)}')

In [ ]:
print(f'mean {np.mean(data)}')

In [ ]:
from machinegnostics.magcal.gmodulus import gmodulus
from machinegnostics.magcal.gvar import gvariance
from machinegnostics.magcal.gacov import gautocovariance
from machinegnostics.magcal import gcorrelation, gvariance, gmodulus, gautocovariance, gcovariance

In [ ]:
data = np.array([1, 1, 1, 1.3, 1.1, 1, 1.4])

In [ ]:
# Using function directly
g_median_quant = gmedian(data, case='j')
print(f"i G-median: {g_median_quant:.4f}")

g_median_esti = gmedian(data, case='i')
print(f"j G-median: {g_median_esti:.4f}")

In [ ]:
Mi = gmodulus(data, case='i')
Mj = gmodulus(data, case='j')



In [ ]:
print(f'Mi {Mi}, Mj {Mj}')

In [ ]:
gvar_i = gvariance(data, 'i')
gvar_j = gvariance(data, 'j')

In [ ]:
print(f'Gvar i:{gvar_i}, Gvar j:{gvar_j}')

In [ ]:
# example of gvariance
data = np.array([1, 2, 3, 4, 5])
gvar_i = gvariance(data, 'i')
gvar_j = gvariance(data, 'j')
print(f'Gvar i:{gvar_i}, Gvar j:{gvar_j}')

In [ ]:
# example of gcorrelation
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([5, 4, 3, 2, 1])
gcor_i = gcorrelation(data1, data2, 'i')
gcor_j = gcorrelation(data1, data2, 'j')
print(f'Gcorrelation i:{gcor_i}, Gcorrelation j:{gcor_j}')

In [ ]:
# example of gautocovariance
data = np.array([1, 2, 3, 4, 5])
gautocov_i = gautocovariance(data, 'i')
gautocov_j = gautocovariance(data, 'j')
print(f'Gautocovariance i:{gautocov_i}, Gautocovariance j:{gautocov_j}')
# example of gcovariance
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([5, 4, 3, 2, 1])
gcov_i = gcovariance(data1, data2, 'i')
gcov_j = gcovariance(data1, data2, 'j')
print(f'Gcovariance i:{gcov_i}, Gcovariance j:{gcov_j}')
# example of gmodulus
data = np.array([1, 2, 3, 4, 5])
gmod_i = gmodulus(data, 'i')
gmod_j = gmodulus(data, 'j')
print(f'Gmodulus i:{gmod_i}, Gmodulus j:{gmod_j}')
# example of gmedian
data = np.array([1, 2, 3, 4, 5])
gmed_i = gmedian(data, 'i')
gmed_j = gmedian(data, 'j')
print(f'Gmedian i:{gmed_i}, Gmedian j:{gmed_j}')
# example of gcorrelation
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([5, 4, 3, 2, 1])
gcor_i = gcorrelation(data1, data2, 'i')
gcor_j = gcorrelation(data1, data2, 'j')
print(f'Gcorrelation i:{gcor_i}, Gcorrelation j:{gcor_j}')

In [ ]:
data = np.array([-100, -2, 3, 4, 5])

# gnosticm median by np.median
statistical_median = np.median(data)
print(f"Statistical median: {statistical_median}")
# gnosticm median by gmedian
gmedian_i = gmedian(data, 'i')
print(f"Gnostic median (i): {gmedian_i}")

In [ ]:
from src.metrics import robr2, gmmfe, divI, evalMet, hc

In [ ]:
# Example data
y = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
y_fit = np.array([0.9, 2.1, 2.9, 4.2, 4.8])
weights = np.array([1, 1, 1, 1, 1])

# Calculate the robust R-squared value
robust_r2 = robr2(y, y_fit, weights)
print(f"Robust R-squared: {robust_r2:.4f}")

# Calculate the GMMFE
gmmfe_value = gmmfe(y, y_fit)
print(f"GMMFE: {gmmfe_value:.4f}")

# Calculate the divergence
divergence_value = divI(y, y_fit)
print(f"Divergence: {divergence_value:.4f}")

# Calculate the evaluation metrics
metrics = evalMet(y, y_fit, weights)
print(f"Evaluation Metrics: {metrics}")

# hc
hc_value = hc(y, y_fit)
print(f"hc: {hc_value:.4f}")

In [ ]:
import numpy as np
from sklearn.metrics import r2_score

# Simulate more complex data
np.random.seed(42)  # For reproducibility
x = np.linspace(0, 10, 20)
y = 2.5 * np.sin(x) + 0.5 * x + np.random.normal(scale=.2, size=len(x))  # Non-linear data with noise
# adding specific outlier 
y[5] = 0.55  # Adding an outlier
y[7] = 7.5  # Adding another outlier
y[13] = 12.9 # Adding another outlier
# y[5] = 11.5 # Adding another outlier
y_fit = 2.5 * np.sin(x) + 0.5 * x  # Ideal fit (without noise)
weights = np.random.uniform(0.8, 1.2, size=len(x))  # Random weights

# Calculate the robust R-squared value
robust_r2 = robr2(y, y_fit, weights)
print(f"Robust R-squared: {robust_r2:.4f}")

# Calculate the GMMFE
gmmfe_value = gmmfe(y, y_fit)
print(f"GMMFE: {gmmfe_value:.4f}")

# Calculate the divergence
divergence_value = divI(y, y_fit)
print(f"Divergence: {divergence_value:.4f}")

# Calculate the evaluation metrics
metrics = evalMet(y, y_fit, weights)
print(f"Evaluation Metrics: {metrics}")

In [ ]:
from src.models import RobustRegressor

mgr = RobustRegressor(degree=6)

mgr.fit(x, y)

y_pred = mgr.predict(x)

In [ ]:
# sk learn polinomial regression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# Create a polynomial regression model
degree = 6
polyreg = make_pipeline(PolynomialFeatures(degree), LinearRegression())
polyreg.fit(x.reshape(-1, 1), y)
y_pred_sklearn = polyreg.predict(x.reshape(-1, 1))

In [ ]:
# sklearn's R-squared value
r2 = r2_score(y, y_pred)
print(f"R-squared - MG: {r2:.4f}")

# sklearn's R-squared value for polynomial regression
r2_sklearn = r2_score(y, y_pred_sklearn)
print(f"R-squared - sklearn: {r2_sklearn:.4f}")

# robust regressor evaluation
robust_r2 = robr2(y, y_pred, mgr.weights)
print(f"Robust R-squared: {robust_r2:.4f}")
# Calculate the GMMFE
gmmfe_value = gmmfe(y, y_pred)
print(f"GMMFE: {gmmfe_value:.4f}")
# Calculate the divergence
divergence_value = divI(y, y_pred)
print(f"Divergence: {divergence_value:.4f}")
# Calculate the evaluation metrics
metrics = evalMet(y, y_pred, mgr.weights)
print(f"Evaluation Metrics: {metrics}")

In [ ]:
# plot y and y_fit with error bars
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(x, y, label='Observed Data', color='blue', alpha=0.6)
plt.plot(x, y_fit, label='True Line Function', color='red', linewidth=2)
# plot y_pred from robust regressor
plt.plot(x, y_pred, label='Mango Fit', color='green', linestyle='--', linewidth=2)
# plot y_pred from sklearn
plt.plot(x, y_pred_sklearn, label='Sklearn Fit', color='orange', linestyle='--', linewidth=2)
plt.errorbar(x, y, yerr=0.5, fmt='o', color='gray', alpha=0.5, label='Error Bars')
plt.title('Observed Data vs Fitted Line')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend()
plt.grid()
plt.show()

In [ ]:
from machinegnostics.metrics import gcorrelation
import numpy as np

# Example 1: Estimation case (should be close to 1 for linear relationship)
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
y = np.array([0.9, 2.1, 2.9, 4.2, 4.8])
gcor_i = gcorrelation(x, y)
print(f"Estimation correlation (case='i'): {gcor_i}")

# Example 2: Quantification case (should be positive for strong relationship)
a = np.array([10.1, 10.3, 9.8, 10.2, 10.0])
b = np.array([5.1, 5.2, 4.9, 5.3, 5.0])
gcor_j = gcorrelation(a, b)
print(f"Quantification correlation (case='j'): {gcor_j}")

In [ ]:
# check with other correlation
from scipy.stats import pearsonr, spearmanr
# Pearson correlation
pearson_corr, _ = pearsonr(x, y)
print(f"Pearson correlation: {pearson_corr}")

# for and b
pearson_corr, _ = pearsonr(a, b)
print(f"Pearson correlation: {pearson_corr}")

In [ ]:
import numpy as np
import pandas as pd
from machinegnostics.metrics import gcorrelation
# from machinegnostics.magcal.gcor import gcorrelation

# Example 2: Multiple pairs (2D arrays)
X = np.array([
    [1.0, 2.0, 3.0, 4.0, 5.0],   # 'a'
    [2.0, 3.0, 4.0, 5.0, 6.0]    # 'b'
])
Y = np.array([
    [0.9, 2.1, 2.9, 4.2, 4.8],   # 'j'
    [1.8, 3.2, 4.1, 5.1, 6.2]    # 'k'
])

# Assign row/column names
x_names = ['a', 'b']
y_names = ['j', 'k']

# Compute correlation matrix
corr_matrix = gcorrelation(X, Y)

# Convert to DataFrame for labeled output
df_corr = pd.DataFrame(corr_matrix, index=x_names, columns=y_names)
print(corr_matrix)
df_corr

In [2]:
# Example: Classification metrics and report comparison

import numpy as np
from machinegnostics.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
)
from machinegnostics.models import LogisticRegressor

# Simulate a simple binary classification dataset
y_true = np.array([0, 1, 1, 0, 1, 0, 1, 1, 0, 0])
y_pred = np.array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

print("=== ManGo Metrics (manual prediction) ===")
print(f"Accuracy:  {accuracy_score(y_true, y_pred):.2f}")
print(f"Precision: {precision_score(y_true, y_pred, average='binary'):.2f}")
print(f"Recall:    {recall_score(y_true, y_pred, average='binary'):.2f}")
print(f"F1 Score:  {f1_score(y_true, y_pred, average='binary'):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))
print("Classification Report:")
print(classification_report(y_true, y_pred))

# Compare with scikit-learn
from sklearn.metrics import accuracy_score as sk_acc, precision_score as sk_prec, recall_score as sk_rec, f1_score as sk_f1, confusion_matrix as sk_cm, classification_report as sk_report

print("\n=== scikit-learn Metrics (manual prediction) ===")
print(f"Accuracy:  {sk_acc(y_true, y_pred):.2f}")
print(f"Precision: {sk_prec(y_true, y_pred):.2f}")
print(f"Recall:    {sk_rec(y_true, y_pred):.2f}")
print(f"F1 Score:  {sk_f1(y_true, y_pred):.2f}")
print("Confusion Matrix:")
print(sk_cm(y_true, y_pred))
print("Classification Report:")
print(sk_report(y_true, y_pred, digits=2))

# Example with LogisticRegressor (fit and predict)
X = np.array([
    [0.1, 1.2],
    [1.1, 0.9],
    [0.2, 1.0],
    [1.0, 1.1],
    [0.9, 0.2],
    [1.2, 0.1],
    [0.3, 1.3],
    [1.3, 0.3],
    [0.4, 1.4],
    [1.4, 0.4]
])
y = np.array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

model = LogisticRegressor()
model.fit(X, y)
y_pred_model = model.predict(X)

print("\n=== ManGo Metrics (LogisticRegressor) ===")
print(f"Accuracy:  {accuracy_score(y, y_pred_model):.2f}")
print(f"Precision: {precision_score(y, y_pred_model, average='binary'):.2f}")
print(f"Recall:    {recall_score(y, y_pred_model, average='binary'):.2f}")
print(f"F1 Score:  {f1_score(y, y_pred_model, average='binary'):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred_model))
print("Classification Report:")
print(classification_report(y, y_pred_model))

print("\n=== scikit-learn Metrics (LogisticRegressor) ===")
print(f"Accuracy:  {sk_acc(y, y_pred_model):.2f}")
print(f"Precision: {sk_prec(y, y_pred_model):.2f}")
print(f"Recall:    {sk_rec(y, y_pred_model):.2f}")
print(f"F1 Score:  {sk_f1(y, y_pred_model):.2f}")
print("Confusion Matrix:")
print(sk_cm(y, y_pred_model))
print("Classification Report:")
print(sk_report(y, y_pred_model, digits=2))

=== ManGo Metrics (manual prediction) ===
Accuracy:  0.70
Precision: 0.75
Recall:    0.60
F1 Score:  0.67
Confusion Matrix:
[[4 1]
 [2 3]]
Classification Report:
Class           Precision    Recall  F1-score   Support
0                    0.67      0.80      0.73         5
1                    0.75      0.60      0.67         5
Avg/Total            0.71      0.70      0.70        10


=== scikit-learn Metrics (manual prediction) ===
Accuracy:  0.70
Precision: 0.75
Recall:    0.60
F1 Score:  0.67
Confusion Matrix:
[[4 1]
 [2 3]]
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.80      0.73         5
           1       0.75      0.60      0.67         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10


=== ManGo Metrics (LogisticRegressor) ===
Accuracy:  0.80
Precision: 0.80
Recall:    0.80
F1 Score:  0.80
Confusion

In [2]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("sklearn Accuracy:", accuracy_score(y_true, y_pred))
print("sklearn Precision:", precision_score(y_true, y_pred))
print("sklearn Recall:", recall_score(y_true, y_pred))
print("sklearn F1:", f1_score(y_true, y_pred))
print("sklearn Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

sklearn Accuracy: 0.7
sklearn Precision: 0.75
sklearn Recall: 0.6
sklearn F1: 0.6666666666666666
sklearn Confusion Matrix:
 [[4 1]
 [2 3]]
